# Generated by Django 5.0.1 on 2024-02-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_id', models.IntegerField(unique=True)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('area', models.FloatField()),
                ('furnishing_status', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
