# Generated by Django 5.0.1 on 2024-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField(unique=True)),
                ('building_name', models.CharField(max_length=500)),
                ('year_of_completion', models.CharField(max_length=5)),
                ('total_floors', models.CharField(max_length=5)),
                ('swimming_pools', models.CharField(max_length=10)),
                ('total_parking_spaces', models.CharField(max_length=10)),
                ('elevators', models.CharField(max_length=5)),
            ],
        ),
    ]
