# Generated by Django 5.0.1 on 2024-02-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_buildinginformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentDetail',
        ),
    ]
