# Generated by Django 5.0.1 on 2024-02-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_projectinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInformation',
        ),
    ]
