# Generated by Django 5.0.1 on 2024-02-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_projectinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinformation',
            old_name='project_id',
            new_name='project_idd',
        ),
        migrations.RemoveField(
            model_name='projectinformation',
            name='completion',
        ),
        migrations.RemoveField(
            model_name='projectinformation',
            name='handover',
        ),
        migrations.RemoveField(
            model_name='projectinformation',
            name='last_inspected',
        ),
        migrations.RemoveField(
            model_name='projectinformation',
            name='project_name',
        ),
    ]
