# Generated by Django 5.0.1 on 2024-02-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_project_id_projectinformation_project_idd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInformation',
        ),
    ]
