# Generated by Django 5.0.1 on 2024-02-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_projectinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_id', models.IntegerField(unique=True)),
                ('developer', models.CharField(max_length=500)),
                ('ownership', models.CharField(max_length=500)),
                ('built_up_area', models.CharField(max_length=50)),
                ('usage', models.CharField(max_length=500)),
                ('balcony_size', models.CharField(max_length=500)),
                ('total_building_area', models.CharField(max_length=500)),
                ('parking_availability', models.CharField(max_length=500)),
            ],
        ),
    ]
