# Generated by Django 5.0.1 on 2024-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_validatedinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True)),
                ('for_rent', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=5000)),
            ],
        ),
    ]
