# Generated by Django 5.0.1 on 2024-02-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_propertydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetail',
            name='detail',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
