# Generated by Django 5.0.1 on 2024-02-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_propertydetail_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinginformation',
            name='year_of_completion',
            field=models.CharField(max_length=6),
        ),
    ]
