# Generated by Django 5.0.1 on 2024-02-27 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_buildinginformation_year_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinformation',
            name='apartment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.apartmentdetail'),
        ),
    ]
