# Generated by Django 5.0.1 on 2024-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_propertydetail_state_propertydetail_sub_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='property_type',
            field=models.CharField(default='rent', max_length=100),
        ),
    ]
