# Generated by Django 5.0.1 on 2024-02-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_propertydetail_property_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyDetail',
        ),
    ]
