# Generated by Django 5.0.1 on 2024-02-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_delete_propertydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('completion', models.CharField(max_length=50)),
                ('added_on', models.CharField(max_length=100)),
                ('state', models.CharField(default='Dubai', max_length=100)),
                ('sub_state', models.CharField(default='Dubai Marina', max_length=100)),
            ],
        ),
    ]
