# Generated by Django 5.0.1 on 2024-02-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_propertydetail_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetail',
            name='rent_frequency',
            field=models.CharField(default='nan', max_length=10),
        ),
    ]
