# Generated by Django 5.0.1 on 2024-02-15 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 7, 16, 14, 994661, tzinfo=datetime.timezone.utc)),
        ),
    ]
