# Generated by Django 5.0.1 on 2024-02-15 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 12, 28, 21, 87523)),
        ),
    ]
