# Generated by Django 5.0.1 on 2024-02-15 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 7, 47, 45, 128179, tzinfo=datetime.timezone.utc)),
        ),
    ]
