# Generated by Django 5.0.1 on 2024-02-15 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 8, 35, 35, 799423, tzinfo=datetime.timezone.utc)),
        ),
    ]
