# Generated by Django 5.0.1 on 2024-02-16 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 9, 57, 0, 711388, tzinfo=datetime.timezone.utc)),
        ),
    ]
