# Generated by Django 5.0.1 on 2024-02-19 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 7, 50, 53, 110650, tzinfo=datetime.timezone.utc)),
        ),
    ]
