# Generated by Django 5.0.1 on 2024-02-19 11:31

import datetime
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 11, 33, 6, 516070, tzinfo=datetime.timezone.utc)),
        ),
    ]
