# Generated by Django 5.0.1 on 2024-02-19 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_remove_user_date_of_birth_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twofa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 12, 11, 34, 312579, tzinfo=datetime.timezone.utc)),
        ),
    ]
