# Generated by Django 5.0.1 on 2024-02-20 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_user_sec_email_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 7, 31, 39, 583300, tzinfo=datetime.timezone.utc)),
        ),
    ]
