# Generated by Django 5.0.1 on 2024-02-22 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_emailotp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 6, 45, 51, 414861, tzinfo=datetime.timezone.utc)),
        ),
    ]
